version: "2.1"

services:

  dokuwiki:

    image: lscr.io/linuxserver/dokuwiki:latest

    container_name: dokuwiki

    environment:

      - PUID=1000

      - PGID=1000

      - TZ=Europe/London

    volumes:
      - ./data:/config/dokuwiki/data
      - ./conf:/config/dokuwiki/conf  

    ports:
      - 80:80

    restart: unless-stopped
